sudo: true
language: generic

matrix:
  include:
    - os: linux
      sudo: required
      env:
        - TARGET="lint"
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y shellcheck
        - sudo apt-get install -y devscripts
      script:
        - make -j $TARGET
    - os: linux
      sudo: required
      env:
        - TARGET="build"
      script:
        - make -j $TARGET
    - os: osx
      osx_image: xcode8
      env:
        - TARGET="build"
      script:
        - make -j $TARGET
    - os: osx
      osx_image: xcode9.2
      env:
        - TARGET="build"
      script:
        - make -j $TARGET
    - os: osx
      osx_image: xcode10.1
      env:
        - TARGET="build"
      script:
        - make -j $TARGET
    - os: osx
      osx_image: xcode10.2
      env:
        - TARGET="build"
      script:
        - make -j $TARGET

notifications:
  email: false
